//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringCountClient.StringCountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringCountService.ICountSecondStirngOccurrenceInFirst")]
    public interface ICountSecondStirngOccurrenceInFirst {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountSecondStirngOccurrenceInFirst/CountSecondStirngOccurrenc" +
            "eInFirstt", ReplyAction="http://tempuri.org/ICountSecondStirngOccurrenceInFirst/CountSecondStirngOccurrenc" +
            "eInFirsttResponse")]
        int CountSecondStirngOccurrenceInFirstt(string first, string second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountSecondStirngOccurrenceInFirst/CountSecondStirngOccurrenc" +
            "eInFirstt", ReplyAction="http://tempuri.org/ICountSecondStirngOccurrenceInFirst/CountSecondStirngOccurrenc" +
            "eInFirsttResponse")]
        System.Threading.Tasks.Task<int> CountSecondStirngOccurrenceInFirsttAsync(string first, string second);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICountSecondStirngOccurrenceInFirstChannel : StringCountClient.StringCountService.ICountSecondStirngOccurrenceInFirst, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountSecondStirngOccurrenceInFirstClient : System.ServiceModel.ClientBase<StringCountClient.StringCountService.ICountSecondStirngOccurrenceInFirst>, StringCountClient.StringCountService.ICountSecondStirngOccurrenceInFirst {
        
        public CountSecondStirngOccurrenceInFirstClient() {
        }
        
        public CountSecondStirngOccurrenceInFirstClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CountSecondStirngOccurrenceInFirstClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountSecondStirngOccurrenceInFirstClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountSecondStirngOccurrenceInFirstClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CountSecondStirngOccurrenceInFirstt(string first, string second) {
            return base.Channel.CountSecondStirngOccurrenceInFirstt(first, second);
        }
        
        public System.Threading.Tasks.Task<int> CountSecondStirngOccurrenceInFirsttAsync(string first, string second) {
            return base.Channel.CountSecondStirngOccurrenceInFirsttAsync(first, second);
        }
    }
}
